### ISSUE TITLE
[EPIC] Applications 엔드포인트 구현

### ISSUE THREAD

**Issue by junlegend** [StockfolioOfficial/back-landing-career#8]
## 요구사항

- 채용 지원하기 API
- 채용 지원 취소하기 API
- Applications API 문서화

## TODO

- [ ] #15 채용 지원하기 스토리
- [ ] #16 채용 지원 취소하기 스토리
- [ ] #17 Applications API 문서화
